apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    repoURL: https://github.com/y7ksh-r/devsecops-gitops.git
    targetRevision: main
    path: ../overlays/dev/node-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
