apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 2
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: <YOUR-ECR>/go-app:prod
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
