apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-sa
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaos-role
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-rb
  namespace: dev
subjects:
- kind: ServiceAccount
  name: chaos-sa
  namespace: dev
roleRef:
  kind: Role
  name: chaos-role
  apiGroup: rbac.authorization.k8s.io
