apiVersion: v1
kind: Service
metadata:
  name: go-app-rollout
  namespace: dev
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  selector:
    app: go-app-rollout
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
  sessionAffinity: None
