apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-app-rollout
  namespace: dev
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause:
            duration: 10
        - setWeight: 50
        - pause:
            duration: 10
  selector:
    matchLabels:
      app: go-app-rollout
  template:
    metadata:
      labels:
        app: go-app-rollout
    spec:
      containers:
        - name: go-app
          image: 288937191843.dkr.ecr.ap-south-1.amazonaws.com/go-app:v2
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
