apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-remediator
  namespace: dev
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: remediator
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: remediator
            image: 288937191843.dkr.ecr.ap-south-1.amazonaws.com/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              kubectl get pods -n dev --no-headers | \
              awk '$3=="Error" || $3=="Failed" {print $1}' | \
              xargs -r kubectl delete pod -n dev
            securityContext:
              allowPrivilegeEscalation: false
              privileged: false
            resources:
              requests:
                cpu: "50m"
                memory: "64Mi"
              limits:
                cpu: "100m"
                memory: "128Mi"
          restartPolicy: OnFailure
