apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: remediator-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: remediator
  namespace: dev
roleRef:
  kind: Role
  name: remediator-role
  apiGroup: rbac.authorization.k8s.io
