apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: falco-exception
  namespace: falco
spec:
  exceptions:
    - policyName: disallow-privileged
      ruleNames:
        - validate-privileged
    - policyName: require-resources
      ruleNames:
        - validate-resources
    - policyName: allow-only-ecr
      ruleNames:
        - validate-ecr-images
  match:
    any:
      - resources:
          kinds:
            - Pod
            - DaemonSet
          namespaces:
            - falco
